[ultraseed]
type = sftp
host = pluto.usbx.me
user = slappywhite98
pass = LqPLSYxmy9YZUtpFgBtOJrpspzG4FvgJfsfPXYYfxEDG_FDP
key_use_agent = true
known_hosts_file = ~/.ssh/known_hosts
ask_password = true
shell_type = unix
md5sum_command = md5sum
sha1sum_command = sha1sum

